---
- name: 'Add Syncthing APT key'
  ansible.builtin.get_url:
    url: 'https://syncthing.net/release-key.gpg'
    dest: '/usr/share/keyrings/syncthing-archive-keyring.gpg'
- name: 'Add Syncthing APT repository'
  ansible.builtin.apt_repository:
    repo:
      'deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg]
      https://apt.syncthing.net/ syncthing stable'
    state: 'present'
- name: 'Install Syncthing'
  ansible.builtin.apt:
    name: 'syncthing'
    state: 'present'
- name: 'Install systemd drop-in files for Syncthing'
  ansible.builtin.copy:
    src: 'syncthing@.service.d/'
    dest: '/etc/systemd/system/syncthing@.service.d'
  notify:
    - 'Reload systemd'
    - 'Restart Syncthing'
- name: 'Create a user for Syncthing'
  ansible.builtin.user:
    name: 'files'
    comment: 'Files'
    shell: '/usr/sbin/nologin'
    home: '/srv/files'
    state: 'present'
- name: 'Ensure that /srv/files does exist'
  ansible.builtin.file:
    path: '/srv/files'
    state: 'directory'
    owner: 'files'
    group: 'files'
    mode: '0755'
- name: 'Enable and start Syncthing'
  ansible.builtin.systemd:
    name: 'syncthing@files'
    enabled: true
    state: 'started'
- name: 'Configure Syncthing'
  become_user: 'files'
  ansible.builtin.shell:
    cmd: 'syncthing cli config {{ item.key }} set {{ item.value }}'
  loop:
    - {key: 'gui raw-address', value: '/run/syncthing/socket'}
    - {key: 'gui raw-unix-socket-permissions', value: '666'}
    - {key: 'gui theme', value: 'black'}
    - {key: 'options global-ann-enabled', value: 'false'}
    - {key: 'options local-ann-enabled', value: 'false'}
    - {key: 'options relays-enabled', value: 'false'}
    - {key: 'options natenabled', value: 'false'}
