---
- name: 'Build git-hooks, git-shell-commands and git-update-mirrors binaries'
  become: false
  local_action:
    module: 'ansible.builtin.shell'
    cmd:
      './make.go build -dir {{ tmpdir.path }} -env prod ./cmd/git-hooks
      ./cmd/git-shell-commands ./cmd/git-update-mirrors'
    chdir: '../../../infra'
- name: 'Copy git-hooks, git-shell-commands and git-update-mirrors binaries'
  ansible.posix.synchronize:
    src: '{{ tmpdir.path }}/{{ item }}'
    dest: '/usr/local/lib/infra/{{ item }}'
    rsync_opts:
      - '--chmod=755'
      - '--chown=root:root'
  loop:
    - 'git-hooks'
    - 'git-shell-commands'
    - 'git-update-mirrors'
- name: 'Create git user'
  ansible.builtin.user:
    name: 'git'
    comment: 'Git'
    shell: '/usr/bin/git-shell'
    home: '/srv/git'
    state: 'present'
- name: 'Ensure that /srv/git does exist'
  ansible.builtin.file:
    path: '/srv/git'
    owner: 'git'
    group: 'git'
    mode: '0755'
- name: 'Copy .gitconfig'
  ansible.builtin.copy:
    src: 'gitconfig'
    dest: '/srv/git/.gitconfig'
    owner: 'git'
    mode: '0644'
- name: 'Symlink Git shell commands'
  become_user: 'git'
  ansible.builtin.shell: '/usr/local/lib/infra/git-shell-commands symlink'
- name: 'Copy systemd unit files for Git maintenance tasks'
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '/etc/systemd/system/{{ item }}'
  notify:
    - 'Reload systemd'
  loop:
    - 'git-gc.service'
    - 'git-gc.timer'
    - 'git-update-mirrors.service'
    - 'git-update-mirrors.timer'
- name: 'Ensure that /usr/local/lib/infra/timers does exist'
  ansible.builtin.file:
    path: '/usr/local/lib/infra/timers'
    state: 'directory'
    mode: '0755'
- name: 'Copy scripts for Git maintenance tasks'
  ansible.builtin.copy:
    src: 'git-gc'
    dest: '/usr/local/lib/infra/timers/git-gc'
    mode: '0755'
- name: 'Enable and start Git maintenance tasks'
  ansible.builtin.systemd:
    name: '{{ item }}'
    enabled: true
    state: 'started'
  loop:
    - 'git-gc.timer'
    - 'git-update-mirrors.timer'
