---
- hosts: 'testlab'
  become: true
  pre_tasks:
    - name: 'Load configuration'
      ansible.builtin.include_vars: 'config.yml'
    - name: 'Create a temporary directory'
      become: false
      local_action:
        module: 'ansible.builtin.tempfile'
        state: 'directory'
      register: 'tmpdir'
    - name: 'Ensure apt cache is up to date'
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: '3600'
  roles:
    - 'base'
    - 'git'
    - 'postgresql' # Must be before miniflux role
    - 'miniflux'
    - 'sshd'
    - 'syncthing'
  post_tasks:
    - name: 'Remove the temporary directory'
      become: false
      local_action:
        module: 'ansible.builtin.file'
        path: '{{ tmpdir.path }}'
        state: 'absent'
  handlers:
    - name: 'Reload systemd'
      ansible.builtin.systemd:
        daemon_reload: true
