# Generated by Django 3.2.9 on 2021-11-02 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_bug_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
