#!/usr/bin/env bash

set -euo pipefail

# Based on https://developer.android.com/ndk/guides/other_build_systems.

export TOOLCHAIN="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64"
case "$GOARCH" in
"arm64")
	export TARGET="aarch64-linux-android"
	;;
"amd64")
	export TARGET="x86_64-linux-android"
	;;
"arm")
	export TARGET="armv7a-linux-androideabi"
	;;
*)
	echo "Not supported."
	exit 1
	;;
esac
export API="21"
echo AR="$TOOLCHAIN/bin/llvm-ar" >>"$GITHUB_ENV"
echo CC="$TOOLCHAIN/bin/$TARGET$API-clang" >>"$GITHUB_ENV"
echo AS="$TOOLCHAIN/bin/$TARGET$API-clang" >>"$GITHUB_ENV"
echo CXX="$TOOLCHAIN/bin/$TARGET$API-clang++" >>"$GITHUB_ENV"
echo LD="$TOOLCHAIN/bin/ld" >>"$GITHUB_ENV"
echo RANLIB="$TOOLCHAIN/bin/llvm-ranlib" >>"$GITHUB_ENV"
echo STRIP="$TOOLCHAIN/bin/llvm-strip" >>"$GITHUB_ENV"
