---
# See https://docs.hetzner.com/cloud/technical-details/faq/#how-are-your-images-set-up.
- name: 'Remove QEMU guest agent'
  ansible.builtin.apt:
    name: 'qemu-guest-agent'
    state: 'absent'
    autoremove: true
    purge: true
- name: 'Install basic packages'
  ansible.builtin.apt:
    pkg:
      - 'git'
      - 'gpg'
      - 'htop'
      - 'molly-guard' # prevents accidental shutdowns (reboots)
      - 'rsync'
      - 'unattended-upgrades'
      - 'vim'
- name: 'Configure unattended upgrades'
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '/etc/apt/apt.conf.d/{{ item }}'
  loop:
    - '20auto-upgrades'
    - '50unattended-upgrades'
- name: 'Ensure that required directories exists'
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'directory'
    mode: '0755'
  loop:
    - '/usr/local/lib/infra'
