name: 'Build commands'
on:
  push:
  pull_request:
jobs:
  build-cmds:
    name: 'Build commands'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        cmd:
          - 'cmdtop'
          - 'renamer'
          - 's'
          - 'sqlplay'
        goos:
          - 'android'
          - 'linux'
        goarch:
          - 'amd64'
          - 'arm64'
        exclude:
          - goos: 'android'
            goarch: 'amd64'
          - goos: 'linux'
            goarch: 'arm64'
    steps:
      - name: 'Check out'
        uses: 'actions/checkout@v3'
      - name: 'Set up Go'
        uses: 'actions/setup-go@v3'
        with:
          go-version: '1.18'
      - name: 'Cache Go dependencies'
        uses: 'actions/cache@v3'
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: "${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}"
      - name: 'Test'
        run: 'script/test cmd/${{ matrix.cmd }}'
      - name: 'Configure toolchain for Android builds'
        env:
          GOARCH: '${{ matrix.goarch }}'
        if: "matrix.goos == 'android'"
        run: 'script/ci-android-ndk'
      - name: 'Build'
        env:
          CGO_ENABLED: '1'
          GOARCH: '${{ matrix.goarch }}'
          GOOS: '${{ matrix.goos }}'
        working-directory: 'cmd/${{ matrix.cmd }}'
        run: 'go build -ldflags="-s -w -buildid=" -trimpath'
      - name: 'Upload as artifact'
        uses: 'actions/upload-artifact@v3'
        with:
          name: '${{ matrix.cmd }}-${{ matrix.goos }}-${{ matrix.goarch }}'
          path: 'cmd/${{ matrix.cmd }}/${{ matrix.cmd }}'
