name: 'Build'
on:
  workflow_dispatch:  
jobs:
  build:
    name: 'Build'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        cmd:
          - 'cmdtop'
          - 'renamer'
          - 'sqlplay'
    steps:
      - name: 'Check out'
        uses: 'actions/checkout@v3'
      - name: 'Set up Go'
        uses: 'actions/setup-go@v3'
        with:
          go-version: '1.18'
      - name: 'Cache Go dependencies'
        uses: 'actions/cache@v3'
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: "${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}"
      - name: 'Build'
        env:
          CGO_ENABLED: '0'
        working-directory: 'cmd/${{ matrix.cmd }}'
        run: 'go build -ldflags="-s -w -buildid=" -trimpath'
      - name: 'Upload as artifact'
        uses: 'actions/upload-artifact@v3'
        with:
          name: '${{ matrix.cmd }}'
          path: 'cmd/${{ matrix.cmd }}/${{ matrix.cmd }}'
